import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/providers/theme-provider";
import LeftSidebar from "@/components/side/left-sidebar";
import { Toaster } from "@/components/ui/toaster";
import LoginProvider from "@/lib/providers/login-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <LoginProvider>
            <div className="flex">
              <LeftSidebar />
              {children}
            </div>
          </LoginProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
